### PR TITLE
Use cache for datastructures of the user/permission management

### PR DESCRIPTION
**Pull request by okraits**
This PR utilizes the rails cache to store the datastructures of the user/permission management of GenieACS GUI. The cache is cleared if there was a change related to users, roles or permissions.

### CODE REVIEW

**Comment by okraits** [comment]
@zaidka Any opinion about this?

**Comment by akcoder** [comment]
Oliver,
Do not confuse lack of time with lack of interest :)

-dan

**Comment by okraits** [comment]
@akcoder Does it take so long to write a short reply? No reply in almost a year doesn't look like much interest.

**Comment by akcoder** [comment]
There could be any number of reasons why Ziad hasn't replied. The email
could be buried in his inbox, he could have other work or life commitments.
Hell, I've personally had emails I've been meaning to reply to for many,
many months sitting in my inbox.

-dan

**Comment by okraits** [comment]
@zaidka Wow, that was an answer :grinning: Thank you!

**Comment by zaidka** [comment]
I'm sorry :( Been very busy and overwhelmed with development and support. I keep postponing things until they get buried and I forget about them.

I have merged this now.

There's a few interesting things that I have been working on in hiding for the past year. Of which is a complete rewrite of the UI and a new API and query language to go with that. Will be sharing more details soon-ish.

Sorry again for not being very responsive. And thanks for the PR.

**Comment by okraits** [comment]
No problem! Slight but important improvement submitted in #102.

**Pull request merged**
